name: Automacao Web

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Rodar automação via Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            brunonathan14/automacao_qazando:v1.0.0

      - name: Upload Relatório Extent
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Automacao-Web
          path: target/extent-report.html